/*
 * generated by Xtext 2.28.0
 */
package group9.gameoflife;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GameOfLifeStandaloneSetup extends GameOfLifeStandaloneSetupGenerated {

	public static void doSetup() {
		new GameOfLifeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
