/*
 * generated by Xtext 2.28.0
 */
package group9.gameoflife.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GameOfLifeUiModule extends AbstractGameOfLifeUiModule {

	public GameOfLifeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
