/*
 * generated by Xtext 2.40.0
 */
package group9.gol.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GoLDSLUiModule extends AbstractGoLDSLUiModule {

	public GoLDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
