/*
 * generated by Xtext 2.40.0
 */
package group9.gol.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import group9.gol.GoLDSLRuntimeModule;
import group9.gol.GoLDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GoLDSLIdeSetup extends GoLDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GoLDSLRuntimeModule(), new GoLDSLIdeModule()));
	}
	
}
