/*
 * generated by Xtext 2.28.0
 */
package group9.gameoflife.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import group9.gameoflife.GameOfLifeRuntimeModule;
import group9.gameoflife.GameOfLifeStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GameOfLifeIdeSetup extends GameOfLifeStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GameOfLifeRuntimeModule(), new GameOfLifeIdeModule()));
	}
	
}
