/*
 * generated by Xtext 2.40.0
 */
package group9.gol;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GoLDSLRuntimeModule extends AbstractGoLDSLRuntimeModule {
}
