/*
 * generated by Xtext 2.40.0
 */
package group9.gol;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GoLDSLStandaloneSetup extends GoLDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new GoLDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
