/*
 * generated by Xtext 2.28.0
 */
package group9.gameoflife.validation;

import org.eclipse.xtext.validation.Check;
import group9.gameoflife.gameOfLife.Condition;
import group9.gameoflife.gameOfLife.Grid;
import group9.gameoflife.gameOfLife.Cell;
import group9.gameoflife.gameOfLife.GameOfLifePackage;

public class GameOfLifeValidator extends AbstractGameOfLifeValidator {

    @Check
    public void checkConditionValue(Condition cond) {
        if (cond.getValue() < 0 || cond.getValue() > 8) {
            error("Neighbor value must be between 0 and 8",
                  GameOfLifePackage.Literals.CONDITION__VALUE);
        }
    }

    @Check
    public void checkDuplicateCells(Grid grid) {
        java.util.Set<String> seen = new java.util.HashSet<>();
        for (Cell c : grid.getCells()) {
            String key = c.getX() + "," + c.getY();
            if (seen.contains(key)) {
                error("Duplicate cell coordinates: (" + c.getX() + "," + c.getY() + ")",
                      GameOfLifePackage.Literals.GRID__CELLS);
            } else {
                seen.add(key);
            }
        }
    }

    @Check
    public void checkNonNegativeCell(Cell cell) {
        if (cell.getX() < 0 || cell.getY() < 0) {
            error("Cell coordinates must be non-negative",
                  GameOfLifePackage.Literals.CELL__X); // or CELL__Y
        }
    }
}

